on:
  workflow_call:
    inputs:
      go-version:
        type: string
        required: false
        default: "1.17.8"
      entry-point:
        type: string
        required: false
        default: ""
        description: |
          Directory path where app executable stored, a small main function -
          entry point
      module-path:
        type: string
        required: true
      binary-name:
        type: string
        required: true
      GOFLAGS:
        type: string
        required: false
        default: -mod=vendor
      golangci-create-default:
        type: boolean
        required: false
        default: true
      golangci-version:
        type: string
        required: false
        default: latest

env:
  GOFLAGS: ${{ inputs.GOFLAGS }}

jobs:
  check:
    name: Lint and check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
        with:
          go-version: ${{ inputs.go-version }}
      - name: Create default golangci-lint config if no config exists
        uses: "../actions/create-golangci-config"
        if: ${{ inputs.golangci-create-default }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@b517f99ae23d86ecc4c0dec08dcf48d2336abc29
        with:
          version: ${{ inputs.golangci-version }}
          working-directory: ${{ inputs.module-path }}
          args: -v

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
        with:
          go-version: ${{ inputs.goVersion }}
      - name: go test with coverage and race check
        working-directory: ${{ inputs.module-path }}
        run: go test -race -cover ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
        with:
          go-version: ${{ inputs.goVersion }}
      - name: Building binary
        uses: "../actions/go-build-static"
        with:
          git-commit: ${{ github.sha }}
          binary-name: ${{ inputs.binary-name }}
          working-directory: ${{ inputs.module-path }}
          entry-point: ${{ inputs.entry-point }}
