on:
  workflow_call:
    inputs:
      goVersion:
        type: string
        required: false
        default: "1.17.8"
      MAIN_APP_ENTRY:
        type: string
        required: false
        default: ""
        description: |
          Directory path where app executable stored, a small main function -
          entry point
      modulePath:
        type: string
        required: true
      BINARY_NAME:
        type: string
        required: true
      GOFLAGS:
        type: string
        required: false
        default: -mod=vendor
      golangciCreateDefault:
        type: boolean
        required: false
        default: true
      golangciDockerLabel:
        type: string
        required: false
        default: latest

env:
  GOFLAGS: ${{ inputs.GOFLAGS }}

jobs:
  check:
    name: Lint and check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
        with:
          go-version: ${{ inputs.goVersion }}
      - name: Install tooling
        run: |
          GOFLAGS= go install golang.org/x/lint/golint@latest
          GOFLAGS= go install github.com/kisielk/errcheck@latest
      - name: Create default golangci-lint bin
      - name: Create default golangci-lint config if no config exists
        uses: "../actions/create-golangci-config"
        if: ${{ inputs.golangciCreateDefault }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@b517f99ae23d86ecc4c0dec08dcf48d2336abc29
        with:
          version: ${{ inputs.golangciVersion }}
          working-directory: ${{ inputs.modulePath }}
          args: -v

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
        with:
          go-version: ${{ inputs.goVersion }}
      - name: go test with coverage and race check
        working-directory: ${{ inputs.modulePath }}
        run: go test -race -cover ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
        with:
          go-version: ${{ inputs.goVersion }}
      - name: Building binary
        env:
          GIT_COMMIT: ${{ github.sha }}
          BINARY_NAME: ${{ inputs.BINARY_NAME }}
        working-directory: ${{ inputs.modulePath }}
        shell: bash
        run: |
          CGO_ENABLED=0 \
          GOOS=linux \
          GOARCH=amd64 \
          go build \
            -a \
            -installsuffix cgo \
            -v \
            -o ${{ inputs.BINARY_NAME }} \
            -ldflags "\
              -X main.commitID=${GIT_COMMIT} \
              -X main.name=${{ inputs.BINARY_NAME }} \
              -X 'main.buildDate=$(date)'" \
            ${{ inputs.MAIN_APP_ENTRY }}
