name: Release Drafter

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: 'Token'
        required: true

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main

# See: https://github.com/release-drafter/release-drafter