---
name: Update Infrastructure Repo to reflect changes after merge
on:
  workflow_call:
    inputs:
      environment-matrix-json:
        required: true
        type: string
        description: |
          on line json build matrix in the form of
          [ { "environment":"env name","auto-merge": "true/false","auto-approve":"true/false"},  { "environment":"env name","auto-merge": "true/false","auto-approve":"true/false"}, { "merge-method": "squash/merge/rebase"} ]
          note: all the values of the keys will be accessable in the script environment, for example you can point to the env variable $environment but be aware the rules for
          environment variables apply, for example you can not have dashes in the name or else the variable will not load correctly when you use it in the script.
      working-directory:
        required: false
        type: string
        description: Path where to run
        default: update-infrastructure-repo-workflow
      source-github-repo:
        required: true
        type: string
        description: Github Repo to clone
      update-script:
        required: true
        type: string
      write-back-application-id:
        required: false
        type: number
        default: 172868

    secrets:
      approve-pr-token:
        required: false
      write-back-app-pem:
        required: true
        description: Private PEM for usage of the write_back_app in github

jobs:
  update-infrastructure:
    name: Update Infrastructure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(inputs.environment-matrix-json) }}

    steps:
      - name: Generate token for writeback to pr
        id: generate_token
        # v1.5.1
        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06
        with:
          app_id: 172868
          private_key: ${{ secrets.write-back-app-pem }}

      - name: Clone the repostory
        # v3.0.0
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.source-github-repo }}
          ref: main
          token: ${{ steps.generate_token.outputs.token }}
          path: ${{ inputs.working-directory }}
          fetch-depth: 0

      - name: Run Script
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.update-script }}
        env: ${{ matrix }}

      - name: Create Pull Request
        id: cpr
        # v3.14.0
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
          path: ${{ inputs.working-directory }}
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: Update infrastructure ${{ matrix.environment }} to ${{ github.sha }}
          title: Update infrastructure ${{ matrix.environment }} to ${{ github.sha }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: update-${{ matrix.environment }}-to-${{ github.sha }}
          delete-branch: true
          body: |
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr

      - name: Set pull request to auto-merge
        if: ${{ matrix.auto-merge == 'true' }}
        # v1.2.0
        uses: peter-evans/enable-pull-request-automerge@127dd0d855f673047637945655ee76f0e9f239fe
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          repository: ${{ inputs.source-github-repo }}
          merge-method: ${{ matrix.merge-method || 'squash' }}

      - name: Approve Pull Request
        if: ${{ matrix.auto-approve == 'true' }}
        # v1.1.1
        uses: juliangruber/approve-pull-request-action@6b8b2f82d50cea1e4329bcdfe940a6ceccbe528e
        with:
          github-token: ${{ secrets.approve-pr-token }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          repo: ${{ inputs.source-github-repo }}
