---
name: Update Infrastructure Repo to reflect changes after merge
on:
  workflow_call:
    inputs:
      environment-matrix-json:
        required: true
        type: string
        description: |
          on line json build matrix in the form of
          [ { "environment":"env name","auto-merge": "true/false","auto-approve":"true/false"},  { "environment":"env name","auto-merge": "true/false","auto-approve":"true/false"} ]
          note: all the values of the keys will be accessable in the script environment, for example you can point to the env variable $environment
      working-directory:
        required: false
        type: string
        description: Path where to run
        default: update-infrastructure-repo-workflow
      source-github-repo:
        required: true
        type: string
        description: Github Repo to clone
      update-script:
        required: true
        type: string
      write-back-application-id:
        required: false
        type: number
        default: 172868

    secrets:
      approve-pr-token:
        required: false
      write-back-app-pem:
        required: true
        description: Private PEM for usage of the write_back_app in github

jobs:
  update-infrastructure:
    name: Update Infrastructure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(inputs.environment-matrix-json) }}

    steps:
      - name: Generate token for writeback to pr
        id: generate_token
        # v1.5.1
        uses: tibdex/github-app-token@7ce9ffdcdeb2ba82b01b51d6584a6a85872336d4
        with:
          app_id: 172868
          private_key: ${{ secrets.write-back-app-pem }}


      - name: Clone the repostory
        # v3.0.0
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          repository: ${{ inputs.source-github-repo }}
          ref: main
          token: ${{ steps.generate_token.outputs.token }}
          path: ${{ inputs.working-directory }}
          fetch-depth: 0

      - name: Run Script
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.update-script }}
        env: ${{ matrix }}

      - name: Create Pull Request
        id: cpr
        # v3.14.0
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672
        with:
          path: ${{ inputs.working-directory }}
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: Update infrastructure ${{ matrix.environment }} to ${{ github.sha }}
          title: Update infrastructure ${{ matrix.environment }} to ${{ github.sha }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: update-${{ matrix.environment }}-to-${{ github.sha }}
          delete-branch: true
          body: |
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr


      - name: Set pull request to auto-merge
        if: ${{ matrix.auto-merge == 'true' }}
        # v1.2.0
        uses: peter-evans/enable-pull-request-automerge@21d45e1c52f5d111d2019b5d33f953ed2e735c46
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          repository: ${{ inputs.source-github-repo }}
          merge-method: squash


      - name: Approve Pull Request
        if: ${{ matrix.auto-approve == 'true' }}
        # v1.1.1
        uses: juliangruber/approve-pull-request-action@2e3a01bea165781841c2ebaf0a8b3202557383e2
        with:
          github-token: ${{ secrets.approve-pr-token }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          repo: ${{ inputs.source-github-repo }}
