---
name: Update Coop Norge Repository
on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        description: Path where to run
        default: update-repository-workflow
      source-github-repo:
        required: true
        type: string
        description: Github repository to clone
      branch-name:
        required: true
        type: string
      pull-request-title:
        required: true
        type: string
      pull-request-commit-message:
        required: true
        type: string
      auto-merge:
        required: false
        type: boolean
        default: false
      auto-approve:
        required: false
        type: boolean
        default: false
      merge-method:
        required: false
        type: string
      update-script:
        required: true
        type: string
      write-back-application-id:
        required: false
        type: number
        default: 172868
      
    secrets:
      approve-pr-token:
        required: false
      write-back-app-pem:
        required: true
        description: Private PEM for usage of the write_back_app in github

jobs:
  update-infrastructure:   
    name: Update Repository
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate token for writeback to pr
        id: generate_token
        # v2.1.0
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        with:
          app_id: ${{ inputs.write-back-application-id }}
          private_key: ${{ secrets.write-back-app-pem }}
    
      - name: Clone the repostory
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          repository: ${{ inputs.source-github-repo }}
          ref: main
          token: ${{ steps.generate_token.outputs.token }}
          path: ${{ inputs.working-directory }}
          fetch-depth: 0

      - name: Run Script
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.update-script }}
    
      - name: Set branch name
        id: branch_name
        run: echo "BRANCH=${{ inputs.branch-name }}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: pull_request
        # v6.0.0
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50
        with:
          path: ${{ inputs.working-directory }}
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: ${{ inputs.pull-request-commit-message }}
          title: ${{ inputs.pull-request-title }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: ${{ steps.branch_name.outputs.BRANCH }}
          delete-branch: true
          body: |
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr

      - name: Set pull request to auto-merge
        if: ${{ inputs.auto-merge }} && ${{ steps.pull_request.outputs.pull-request-number }}
        # v3.0.0
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request-number: ${{ steps.pull_request.outputs.pull-request-number }}
          repository: ${{ inputs.source-github-repo }}
          merge-method: ${{ inputs.merge-method || 'squash' }}
          
      - name: Approve Pull Request
        if: ${{ inputs.auto-approve }} && ${{ steps.pull_request.outputs.pull-request-number }}
        # v2.0.4
        uses: juliangruber/approve-pull-request-action@dcc4effb325c0b503408619918d56e40653dcc91
        with:
          github-token: ${{ secrets.approve-pr-token }}
          number: ${{ steps.pull_request.outputs.pull-request-number }}
          repo: ${{ inputs.source-github-repo }}
          