---
name: Update Infrastructure Repo to reflect changes after merge
on:
  workflow_call:
    inputs:
      environment-matrix-json:
        required: true
        type: string
        description: |
          on line json build matrix in the form of
          [ { "environment":"env name","auto-merge": "true/false","auto-approve":"true/false"},  { "environment":"env name","auto-merge": "true/false","auto-approve":"true/false"}, { "merge-method": "squash/merge/rebase"} ]
          note: all the values of the keys will be accessable in the script environment, for example you can point to the env variable $environment but be aware the rules for
          environment variables apply, for example you can not have dashes in the name or else the variable will not load correctly when you use it in the script.
      working-directory:
        required: false
        type: string
        description: Path where to run
        default: update-infrastructure-repo-workflow
      source-github-repo:
        required: true
        type: string
        description: Github Repo to clone
      update-script:
        required: true
        type: string
      write-back-application-id:
        required: false
        type: number
        default: 172868
      service:
        required: false
        type: string
        default: ""

    secrets:
      approve-pr-token:
        required: false
      write-back-app-pem:
        required: true
        description: Private PEM for usage of the write_back_app in github

jobs:
  update-infrastructure:
    name: Update Infrastructure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(inputs.environment-matrix-json) }}

    steps:
      - name: Generate token for writeback to pr
        id: generate_token
        # v1.5.1
        uses: actions/create-github-app-token@v1.9.3
        with:
          app-id: 172868
          private-key: ${{ secrets.write-back-app-pem }}
          owner: coopnorge
      - name: Clone the repostory
        # v3.0.0
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.source-github-repo }}
          ref: main
          token: ${{ steps.generate_token.outputs.token }}
          path: ${{ inputs.working-directory }}
          fetch-depth: 0

      - name: Run Script
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.update-script }}
        env: ${{ matrix }}

      - name: Set branch name
        id: set-branch-name
        run: |
          if [ "${{ inputs.service }}" != "" ]
          then
            echo "BRANCH=update-${{ inputs.service }}-${{ matrix.environment }}-to-${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "BRANCH=update-${{ matrix.environment }}-to-${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        id: cpr
        # v3.14.0
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e
        with:
          path: ${{ inputs.working-directory }}
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: Update infrastructure ${{ matrix.environment }} to ${{ inputs.service }}:${{ github.sha }}
          title: Update infrastructure ${{ matrix.environment }} to ${{ inputs.service }}:${{ github.sha }}
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          branch: ${{ steps.set-branch-name.outputs.BRANCH }}
          delete-branch: true
          body: |
            Changes from ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}

            ${{ github.event.head_commit.message }}

          labels: |
            automated pr

      - name: Set pull request to auto-merge
        if: ${{ matrix.auto-merge == 'true' }}
        # v1.2.0
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          repository: ${{ inputs.source-github-repo }}
          merge-method: ${{ matrix.merge-method || 'squash' }}

      - name: Approve Pull Request
        if: ${{ matrix.auto-approve == 'true' }}
        # v1.1.1
        uses: juliangruber/approve-pull-request-action@b71c44ff142895ba07fad34389f1938a4e8ee7b0
        with:
          github-token: ${{ secrets.approve-pr-token }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          repo: ${{ inputs.source-github-repo }}
